nuxt/create-nuxt-app

- template/frameworks/vuetify/plugins/vuetify.js
When upgrading Vuetify to version `1.0.0-beta.5`, I received the error "Colors can only be numbers or strings, recieved Object instead". That error is caused by the usage of `colors.amber`, which is an object.
> Fix Vuetify 1.0.0 color declaration error.

- template/_package.json
When I run:
```bash
npm i --production && npm start
```
I got this error:
```
sh: 1: cross-env: not found
```
Therefore I think `cross-env` should be placed in `"dependencies"`.
> cross-env dependency in NODE_ENV=production

- template/_package.json
- template/nuxt/pages/index.vue
Tailwind v0.6.6 allows `@apply` rules in `.vue` single file components so I thought upgrading it as the base version would be beneficial.
However, there are syntax errors from the linter when implementing postcss imports inside components, so adding `<style lang="postcss">` fixes that. In doing that, we'd need to add that test in `nuxt.config.js` with [these rules](https://github.com/nuxt/nuxt.js/issues/3231#issuecomment-381885334) as well.
> fix: tailwind dependency

- template/frameworks/adonis/app/Controllers/Http/NuxtController.js
- template/frameworks/feathers/server/middleware/nuxt.js
- template/frameworks/micro/server/micro.config.js
- template/server/index-express.js
- template/server/index-koa.js
With Nuxt 2.0's release, the `nuxt-edge` dependency is invalid. Changed server template imports to reflect that. Taking into account previous PRs regarding this issue, I've omitted changes from those.
> fix: Cannot find module 'nuxt-edge'

- template/server/index-koa.js
server uses nuxt-edge module, but installed nuxt, so app crashed when npm start
> fix miss nuxt-edge module error

- template/_package.json
- template/frameworks/vuetify/components/Logo.vue
- template/frameworks/vuetify/components/VuetifyLogo.vue
- template/nuxt/components/Logo.vue
- template/nuxt/layouts/default.vue
- template/nuxt/nuxt.config.js
- template/nuxt/pages/index.vue
This PR should resolve the errors that are thrown by the default template when users enable the prettier option during project creation.
> Fix linting thrown from default template when enabling prettier option, container centering when enabling tailwind option

- template/nuxt/pages/index.vue
When running a vanilla NUXT app, prettier complains of the new line at the top of the style.
```
ERROR in ./pages/index.vue
Module Error (from ./node_modules/eslint-loader/index.js):
C:\---\ratest\pages\index.vue
36:1  error  Delete `⏎`  prettier/prettier
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
i.e.
```
<style>
*** THIS LINE ***
.container {
min-height: 100vh;
display: flex;
justify-content: center;
align-items: center;
text-align: center;
}
```
> Remove unwanted \n

- template/nuxt/nuxt.config.js
Like `vuetify`, `element-ui` needs their lib to be transpiled by Nuxt.
`ElementUI` seems to not work at all and throws an error without this fix.
> fix(element-ui): missing element-ui build transpile

- template/nuxt/static/README.md
I realised that `/static/README.md` was deployed to 3 different websites of ours. It's easy overlook the fact, becoming security concern. 
This simple change might help other people stay more secure.
> Instruct people to delete README.md from /static before production deploy

- template/frameworks/feathers/server/middleware/nuxt.js
- template/server/index-express.js
- template/server/index-koa.js
- template/server/index-micro.js
If app is generated with `--edge` flag require `nuxt-edge` instead of `nuxt`. Else console outputs `Error: Cannot find module 'nuxt'`
> fix: require nuxt-edge instead of nuxt

- template/nuxt/nuxt.config.js
When creating an app with the current config, the file ends up like this:
```javascript
modules: [
, // Linter does not like this...
'nuxt-buefy',
'@nuxtjs/pwa'
],
```
So this update would change the file to look like this:
```javascript
modules: [
'nuxt-buefy',
'@nuxtjs/pwa', // Last trailing comma
],
```
> Move commas to after module name

- template/frameworks/express/server/index.js
`nuxt.options.server` overwrites host and port.
Therefore, we deleted the initial value and modified it to a concise
writing style.
> Fix initial value of Express host and port

- saofile.js
Removed `--` to fix the following warnings.
`warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.`
> Remove `--` when using yarn

- template/nuxt/nuxt.config.js
Changed axios options reference link from https://github.com/nuxt-community/axios-module#options to https://axios.nuxtjs.org/options
> Axios options reference link corrected

- template/frameworks/iview/pages/index.vue
- template/nuxt/pages/index.vue
I noticed that both index.vue pages were using sections for the main page containers instead of div elements like the W3C spec suggests.
Here is a snippet from the spec:
> The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element’s contents would be listed explicitly in the document’s outline. 
[https://www.w3.org/TR/html/sections.html#example-1a704a1d](url)
> Swapping section container elements to div elements per W3C spec

- template/gitignore
When using create-nuxt-app I've found that many **.DS_Store** files are staged to commit and one **.editorconfig** from Visual Studio Code.
I think that it would save a few seconds of developers life and what's also important, in default Vue template .gitignore file **.DS_Store** is on the top of it.
> chore: gitignore minor fixes

- template/_package.json
At the moment iview is matched to only 3.1.5. Allow it to match the latest minor release, as per semver.
> fix: iview UI package version match

- cli.js
- package.json
- yarn.lock
```console
$ yarn create nuxt-app --help
...
success Installed "create-nuxt-app@2.7.1" with binaries:
- create-nuxt-app
> Generating Nuxt.js project in /Users/evila/--help
? Project name (--help) 
```
The `target path` is `/User/evila/--help` obviously not right 🤔
> feat(cli): use cac for cli

- cli.js
Presently, the `usage` information shown as part of the help text lacks reference to `options`.
`Present state`
```md
Usage: create-nuxt-app [out-dir]
```
`Updated To`
```md
Usage: create-nuxt-app [out-dir] [options]
```
> chore: update usage information

- template/README.md
Check out is the proper verbiage for this particular sentence.
> 📘fix(readme): spelling fix

- template/gitignore
According to https://editorconfig.org/: 
> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.
I would assume that this file is expected to be commited into source control.
> Remove .editorconfig from .gitignore

- template/nuxt/components/Logo.vue
Closes #362 
I got rid of the old logo animation, maybe we could add a small fade-in effect to make up or it?
> feat: update logo component with the new nuxt logo

- template/gitignore
We don't ignore logs directory If a project has logging api. (like `pages/app/logs/index.vue`)
So I suggest logs directory should ignore only root logs directory.
Thank you!
> Should only ignore root logs directory

- saofile.js
- template/README.md
Fixed npm installation command.
Expected:
```bash
$ npm install
```
Actual:
```bash
$ npm run install
```
> docs(readme): Fix installation command

- template/_stylelint.config.js
Change `rules` to Object from Array
>The rules property is an object whose keys are rule names and values are rule configurations. Each rule configuration fits one of the following formats
https://stylelint.io/user-guide/configuration
> fix: stylelint config rules is object

- template/frameworks/adonis/providers/NuxtProvider.js
- template/frameworks/express/server/index.js
- template/frameworks/fastify/server/index.js
- template/frameworks/feathers/server/index.js
- template/frameworks/koa/server/index.js
- template/frameworks/micro/server/index.js
https://github.com/nuxt/typescript/issues/215
https://github.com/nuxt/create-nuxt-app/issues/375
nuxt/typescript handle store ts file in `await nuxt.ready()`.
It should be called by every environment
> fix: nuxt.ready is not called in dev mode

- template/frameworks/vuetify/layouts/default.vue
The copyright year is now 2019, should be 2020.
> fix(templates): Vuetify copyright year

- packages/create-nuxt-app/lib/cli.js
> fix: do not proceed if the target directory exists and is non-empty

- packages/cna-template/template/frameworks/ava/test/e2e/index.spec.js
If you use this config:
You'll get this error:
This PR fixes that error ❤️
> fix: eslint issue with ava

- packages/cna-template/template/frameworks/vuetify/pages/index.vue
v-row is a wrapper component for v-col. It utilizes flex properties to control the layout and flow of its inner columns. [...] This is the 2.x replacement for v-layout in 1.x.
v-col is a content holder that must be a direct child of v-row. This is the 2.x replacement for v-flex in 1.x.
https://vuetifyjs.com/fr-FR/components/grids/#usage
> fix: updated layout to be in par with vuetify 2.x

- README.md
I just spend hours trying to figure out the problem with my nuxt installation. I set up new projects using `npm init nuxt-app` to compare configurations. This gave me nuxt 2.0.0 which as of this writing is quite outdated. At first I assumed the template was simply not up to date, but then I learned, that `npm init` will not use the latest version, but simply the currently installed version. This might be consistent with other npm commands, but it most likely also consistently causes problems like mine. Most people will want to use the latest version, so I would like to add that to the command.
> docs: add `@latest` hint to npm init command

- packages/cna-template/template/nuxt/package.js
Just a minor optimization of the generated package.json. The documentation of nuxt-ts [states](https://typescript.nuxtjs.org/guide/lint.html#configuration): 
> If you're already using `@nuxtjs/eslint-config`, remove it from your dependencies, the Nuxt TypeScript ESLint config includes it.
> feat: don't install @nuxtjs/eslint-config and @nuxtjs/eslint-config-typescript together

- packages/cna-template/template/nuxt/nuxt.config.js
Worked with nuxt for the first time today and found this slight issue. After selecting `bulma` as my css framework of choice, it was weird as to why the external link provided lead to bootstrap-vue.
I made this PR to switch the link to the appropriate channel.
PS - there doesn't seem to be a `https://go.nuxtjs.dev/bulma` link so I just used the main bulma website instead. Feel free to change the link if you see fit 🙂
Cheers
> chore(cna-template): fix link to bulma

- packages/cna-template/template/frameworks/ava/test/e2e/index.spec.js
End to end tests should be as close to the real thing as possible, re-creating a whole separate Nuxt configuration from scratch adds potential for inconsistencies.
Being new to Nuxt I was bashing my head against why Nuxt e2e tests didn't have `$axios` configured, and why my project would fail to evaluate the components I referenced in layout files.
I also noticed that global css didn't work.
All of this because the `nuxt.config.js` wasn't being referenced in the end to end tests.
> fix: e2e tests are configured with project's nuxt.config

- packages/cna-template/template/tsconfig.json
When creating a project with typescript and nuxt content, the types are missing so using `this.$content(...)` throws type errors.
This fixes it by adding `@nuxt/content` types to tsconfig.json as described here https://content.nuxtjs.org/installation/#typescript
> feat: add nuxt content support for typescript

- packages/cna-template/template/tsconfig.json
Fix https://github.com/nuxt/create-nuxt-app/issues/690
Include [@nuxtjs/axios types](https://github.com/nuxt-community/axios-module/tree/master/types) into ts compilation.
> fix(types): include @nuxtjs/axios types

- renovate.json
This PR fixes Oruga configuration for renovate.json. I tested it running renovate locally on another repository with the right configuration, I don't know if there's a better way to test renovate.json configuration without creating pull requests.
> fix: Oruga packagePatterns in renovate.json

- packages/create-nuxt-app/lib/cli.js
The user is greeted with the following message if he/she attempts to create a project in the current directory that is non-empty:-
```sh
Can't create . because there's already a non-empty directory . existing in path.
```
This PR aims at rephrasing the above message such that the directory name shows up instead.
> fix(cli): rephrase not empty directory error message

- README.md
- packages/create-nuxt-app/lib/cli.js
https://github.com/nuxt/create-nuxt-app/pull/778#issuecomment-849063461
cc @clarkdo
> feat(create-nuxt-app): add --overwrite-dir flag

- packages/create-nuxt-app/lib/cli.js
This PR has no related issues.
I added a logic for CNA to show help message instead of raw error stack in case a user (like me 1 hour ago) passes unknown options.
By doing so, the user can find what he/she really wanted and copy it quickly, without running `help` command or seeing documentation.
---
**Explanation of work**
I felt the try-catch block long so I extracted the main part in `run` function.
If you prefer inlined version as before, let me know.
**How I tested**
1. Ran `node lib/cli.js test --unknown-options`, and checked the output (for what I added)
2. Ran `node lib/cli.js test` with `throw new Error('Custom Message')` added before `run` function call, and checked the output (for backward compatibility)
3. Ran `node lib/cli.js test`, and checked the output (for backward …
> feat(cli): add user-friendly exit for unknown options

- packages/cna-template/template/frameworks/github-actions/.github/workflows/ci.yml
Using GitHub Actions displays the following warning:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I have adjusted the template accordingly so that no error is displayed anymore.
None of the points above apply as it is only a small fix.
> fix(cna-template): Fixed GitHub Actions warning
