- template/_package.json
- template/frameworks/tailwind/assets/css/tailwind.css
- template/frameworks/tailwind/tailwind.js
Heya! 👋 
Update the installed version of TailwindCSS to his latest released (0.6.1).
> chore(tailwindcss): update default version

- template/gitignore
> Add .idea to .gitignore

- template/_package.json
This pull request updates Vuetify from v0.17.3 to v1.0.19. After testing this locally I did not come across any issues.
> Update Vuetify to version 1

- sao.js
> Update get started message from NPM only to NPM/Yarn compatible

- template/_package.json
Details about the problem of being with the outdated version can be found in this [issue](https://github.com/buefy/nuxt-buefy/issues/23)
> Update nuxt-buefy version

- package-lock.json
- template/frameworks/adonis/app/Controllers/Http/NuxtController.js
- template/frameworks/feathers/server/middleware/nuxt.js
- template/frameworks/micro/server/micro.config.js
- template/server/index-express.js
- template/server/index-koa.js
When server is `micro` , `micro.config.js` require `nuxt-edge`.
> fix: Cannot find module 'nuxt-edge'

- README.md
- package.json
📖 Some small improvements in the doc (badge / typo / URL)
> Fix documentation

- package.json
- sao.js
- template/nuxt/nuxt.config.js
- template/server/index-express.js
- template/server/index-hapi.js
- template/server/index-koa.js
- yarn.lock
To handle cases when there different markup depending on selected options, so lint --fix will handle it.
Fixed a bunch of lint warnings in config and server files
> feat: run lint --fix as last step of creating new app

- template/server/index-koa.js
Simply migrating this PR https://github.com/nuxt-community/koa-template/pull/39 here.
> Simplify Koa Middleware

- template/frameworks/vuetify/layouts/default.vue
It's almost 2019, but I just noticed this so why not. Might be better long term to make it update automatically but for now please accept this humble PR.
> Update copyright date

- README.md
- sao.js
- template/_package.json
> feat: add "edge" CLI flag to install nuxt-edge

- package.json
- sao.js
- yarn.lock
Fixes #148. I've added the `validate-npm-package-name` package for name validation.
> feat: validate name

- template/frameworks/vuetify/layouts/default.vue
Happy New Year 2019! :christmas_tree:
> docs: Happy New Year! :gift:

- template/frameworks/element-ui/plugins/element-ui.js
> fix(element-ui): update plugin import

- README.md
- saofile.js
- template/_package.json
- template/nuxt/nuxt.config.js
Our agency creates many Nuxt + Tachyons projects so we would find it helpful to include [Tachyons](https://tachyons.io) in ui frameworks list, so I thought to give a try and propose a PR.
> Add tachyons as ui framework

- template/frameworks/vuetify/layouts/default.vue
[fixed vue/html-self-closing] in second edit :)
> [vuetify layout fix] added missing v-spacer before right v-btn

- template/frameworks/jest/.babelrc
fixes import of js files with async/await in jest.setup
> use only @babel/preset-env for jest

- template/_.eslintrc.js
disable till https://github.com/nuxt/create-nuxt-app/pull/195
> fix: disable no cjs rule

- template/_package.json
> Fix to execute script in selected package manager

- saofile.js
Fixes https://github.com/nuxt/nuxt.js/issues/5940
> refactor: show the full out folder relative path

- template/frameworks/adonis/providers/NuxtProvider.js
> fix: Adonis commands always running nuxt build

- template/_.eslintrc.js
> fix: prettier error in vuetify

- template/frameworks/vuetify/assets/variables.scss
https://github.com/nuxt-community/vuetify-module/issues/106
> fix: vuetify variables

- cli.js
- package.json
- yarn.lock
Blocked by https://github.com/saojs/sao/pull/134
> feat: answers option

- README.md
add section "Choose development tools"
> chore(doc): add development tools section in README.md

- template/_stylelint.config.js
Stylelint does not work without rules.
Resolves https://github.com/nuxt/create-nuxt-app/issues/382
> (fix)[template]: Stylelint config

- README.md
update readme to add explanation of static for universal mode
> chore(readme): add static

- packages/cna-template/template/README.md
- packages/cna-template/template/_package.json
- packages/cna-template/template/nuxt/pages/index.vue
- packages/create-nuxt-app/lib/prompts.js
- packages/create-nuxt-app/package.json
- packages/create-nuxt-app/test/index.test.js
- yarn.lock
Suggested by @Atinux , `author` and `description` are unnecessary, this pr is removing the from prompt for a faster app creation flow
> feat(template): remove author and description from prompt

- packages/create-nuxt-app/test/index.test.js
> chore: fix typo in `choiceNames` variable name

- packages/create-nuxt-app/lib/cli.js
> fix: update sao link

- package.json
https://github.com/typicode/husky/issues/884
> chore: use prepare script to install git hooks

- packages/cna-template/template/nuxt/.husky/commit-msg
- packages/cna-template/template/nuxt/.husky/pre-commit
> fix(cna-template): use npx to invoke locally installed binaries

- packages/cna-template/template/frameworks/vant/pages/index.vue
I created a project based on vant and found that there were errors in the contents of demo, such as using url attribute instead of to, and updating vant's official website address instead of iviewui.
thanks!
> fix(template): update vant template demo

- packages/cna-template/template/_.eslintrc.js
Fix https://github.com/nuxt/create-nuxt-app/issues/805
> fix(eslint): no babel config file detected

- README.md
> Fixed typo Continous > Continuous

- packages/cna-template/template/frameworks/jest/jest.config.js
I have fixed an eslint error about quotes.
> style: clean quote

- renovate.json
Address https://github.com/nuxt/create-nuxt-app/pull/837#issuecomment-895800039
This config will create a Dependency Dashboard issue which can be used to manage dependencies updates.
> chore(renovate): use renovate dependency dashboard to approval

- README.md
Fix https://github.com/nuxt/create-nuxt-app/issues/852
> chore(doc): fix links in readme

- packages/cna-template/template/nuxt/package.json
> fix(deps): cannot find module issue (#918)
